server:
  port: 8761

eureka:
  instance:
    hostname: rcdev1
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    preferIpAddress: true

  server:
    enableSelfPreservation: false       # 关闭自我保护模式（缺省为打开）
    evictionIntervalTimerInMs: 60000  # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    peerNodeReadTimeoutMs: 20000

  client:
    ## 是否向注册中心注册自己
    registerWithEureka: false

    ## 设置检索服务。单点不同步其它节点，为false；多点同步其它节点，为true
    fetchRegistry: true

    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@rcdev2:8762/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@rcdev3:8763/eureka/